export enum ErrorCode {
  // 클라이언트 에러 (400-499)
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT = "CONFLICT",

  // 서버 에러 (500-599)
  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",

  // 비즈니스 로직 에러 (커스텀)
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  DOMAIN_VALIDATION_ERROR = "DOMAIN_VALIDATION_ERROR",
  RESOURCE_EXISTS = "RESOURCE_EXISTS",
  RESOURCE_EXPIRED = "RESOURCE_EXPIRED",
}
